name: "Update sources"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run update script
        run: ./update.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          [[ "$(git diff sources.json)" ]] || exit 0
          git add sources.json
          git commit -m "update sources"
          git push
